name: flavourfleet
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+71

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  http: ^0.13.6
  intl: ^0.18.1
  get_it: ^7.2.0
  location: ^4.4.0
  geocoding: ^2.0.5
  auto_route: ^5.0.2
  google_place: ^0.4.7
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  cloud_firestore: ^4.0.2
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.1.1
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^4.3.0
  flutter_login_facebook: ^1.6.2
  geolocator: ^9.0.2
  flutter_vibrate: ^1.3.0
  flutter_displaymode: ^0.6.0

  #ui
  image: ^4.0.17
  lottie: ^2.2.0
  top_snackbar_flutter: ^2.1.1
  sms_autofill: ^2.2.0
  google_fonts: ^4.0.4
  url_launcher: ^6.1.12
  flutter_svg: ^2.0.5
  flutter_remix: ^0.0.3
  connectivity_plus: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.2.19
  flutter_advanced_switch: ^3.0.1
  flutter_share: ^2.0.0
  pull_to_refresh: ^2.0.0
  flutter_masked_text2: ^0.9.1
  image_cropper: ^4.0.1
  floating_draggable_widget: ^2.1.2
  google_maps_flutter: ^2.2.1
  flutter_html: ^3.0.0-alpha.6
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.2.2
  proste_indexed_stack: ^0.2.4
  osm_nominatim: ^2.0.1
  flutter_carousel_slider: ^1.1.0
  jiffy: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.1.0
  upgrader: ^7.0.0
  confetti: ^0.7.0
  card_swiper: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2


#firebase
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  flutter_launcher_icons: ^0.13.1



flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    - assets/
    - assets/temp/
    - assets/images/ui3.png

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/customer.png'